ALTER TABLE live_wall_sessions
  ADD COLUMN is_playing BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN show_cta BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN is_blackout BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;
